# application.yml

spring:
  datasource:
#    url: jdbc:mysql://mysql-81ec6c.pveruntimedev.svc.cluster.local:3306/todo_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://localhost:3306/study_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
#eureka:
#  instance:
#    preferIpAddress: true
#    leaseRenewalIntervalInSeconds: 10
#    leaseExpirationDurationInSeconds: 30
#    metadata-map:
#      VERSION: v1
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8000/eureka/}
#    registryFetchIntervalSeconds: 10
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://register-server.pveruntimedev.svc.cluster.local:8000/eureka/}
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration: # 数据库下划线转驼峰配置
    mapUnderscoreToCamelCase: true


choerodon:
  saga:
    consumer:
      enabled: false # 启动消费端
      thread-num: 2 # saga消息消费线程池大小
      max-poll-size: 200 # 每次拉取消息最大数量
      poll-interval-ms: 1000 # 拉取间隔，默认1000毫秒
